name: core
description: The domain layer of Minima
version: 0.1.0

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  uuid: ^3.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
